[phases.setup]
nixPkgs = ["nodejs-18_x", "chromium", "ffmpeg", "glib", "nss", "nspr", "atk", "at-spi2-atk", "libdrm", "mesa", "libxkbcommon", "libXcomposite", "libXdamage", "libXext", "libXfixes", "libXrandr", "gbm", "pango", "cairo", "asound"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node Yak.js"
